name: build

on:
  release:
    types:
      - published

env:
  CARGO_TERM_COLOR: always

jobs:
  build-corss:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v4
      - name: install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
            toolchain: nightly
            targets: ${{ matrix.target }}
      - name: install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: compile
        run: cross build --release --target=${{ matrix.target }} -p stat_client
      - name: pack unix binary
        run: |
          mkdir -p release-${{ matrix.target }}
          cd release-${{ matrix.target }}
          tar -C ../target/${{ matrix.target }}/release -zcf stat_client-${{ matrix.target }}.tar.gz stat_client
      - name: upload unix binary
        uses: actions/upload-artifact@v4
        with:
          name: realm-${{ matrix.target }}
          path: release-${{ matrix.target }}/stat_client-${{ matrix.target }}.tar.gz